blog/urls.py
from django.urls import path 
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.index, name='index'),
    path('category/<int:category_id>/', views.category_list, name='category_list'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    path('search/', views.search, name='search'),
    path('cloud_disk/',views.cloud_disk, name='cloud_disk'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

from utils.upload import upload_file

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('', include('blog.urls')) ,
    path('uploads/', upload_file, name='uploads'),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "BJLDQE管理后台"
admin.site.index_title = "BJLDQE管理后台"
admin.site.site_title = "管理员已上线"

users/urls.py
from django.urls import path
from . import views

app_name = 'users'   # 定义一个命名空间，用来区分不同应用之间的链接地址
urlpatterns = [ 
    path('login', views.login_view, name='login'),
    path('register/', views.register, name='register'),
    path('active/<active_code>',views.active_user,name='active_user'),
    path('forget_pwd/', views.forget_pwd, name='forget_pwd'),   # 找回密码发送邮件页面
    path('forget_pwd_url/<active_code>', views.forget_pwd_url, name='forget_pwd_url'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('editor_users/', views.editor_users, name='editor_users'), 
    path('logout/', views.logout_view, name='logout'),



]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.loader import render_to_string

# Create your models here.
class Category(models.Model):
    """ 博客的分类模型 """
    name = models.CharField(max_length=32, verbose_name="分类名称")
    desc = models.TextField(max_length=200, blank=True, default='', verbose_name="分类描述")
    add_date = models.DateTimeField(auto_now_add=True, verbose_name="发布时间")
    pub_date = models.DateTimeField(auto_now=True, verbose_name="修改时间")

    class Meta:
        verbose_name = "内容分类"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name
class Tag(models.Model):
    """ 文章标签 """
    name = models.CharField(max_length=10, verbose_name="文章标签")
    add_date = models.DateTimeField(auto_now_add=True, verbose_name="发布时间")
    pub_date = models.DateTimeField(auto_now=True, verbose_name="修改时间")

    class Meta:
        verbose_name = "文章标签"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name
    
class Post(models.Model):
    """ 文章 """
    title = models.CharField(max_length=61, verbose_name="文章标题")
    desc = models.TextField(max_length=200, blank=True, default='', verbose_name="文章描述")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="分类")
    content = models.TextField(verbose_name="文章正文")
    tags = models.ForeignKey(Tag, blank=True, null=True, on_delete=models.CASCADE, verbose_name="文章标签")
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="发布者")
    is_hot = models.BooleanField(default=False, verbose_name="是否热门")   # 手动热门推荐

    pv = models.IntegerField(default=0,verbose_name="阅读量")  # 浏览量
    add_date = models.DateTimeField(auto_now_add=True, verbose_name="发布时间")
    pub_date = models.DateTimeField(auto_now=True, verbose_name="修改时间")

    class Meta:
        verbose_name = "文章"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title
    
class SideBar(models.Model):
    STATUS = (
        (1, '隐藏'),
        (2, '显示')
    )

    DISPLAY_TYPE = (
        (1, '搜索'),
        (2, '最近发布'),
        (3, '最热文章'),
        (4, '最新评论'),
        (5, '文章归档'),
        (6, 'HTML')
    )

    title = models.CharField(max_length=50, verbose_name="标题")
    display_type = models.PositiveIntegerField(default=1, choices=DISPLAY_TYPE, verbose_name="显示类型")
    content = models.CharField(max_length=500, blank=True, default='', verbose_name="内容",
                               help_text="如果设置的不是HTML类型，可为空")
    sort = models.PositiveIntegerField(default=1,  verbose_name="排序", help_text='序号越大越靠前')
    status = models.PositiveIntegerField(default=2, choices=STATUS, verbose_name="状态")
    add_date = models.DateTimeField(auto_now_add=True, verbose_name="发布时间")

    class Meta:
        verbose_name = "侧边栏"
        verbose_name_plural = verbose_name
        ordering = ['-sort']

    def __str__(self):
        return self.title

    
    @classmethod    # 类方法装饰器，这个就变成了这个类的一个方法可以调用
    def get_sidebar(cls):
        return cls.objects.filter(status=2)   # 查询到所有允许展示的模块

    
    @property    # 成为一个类属性，调用的时候不需要后边的（）,是只读的，用户没办法修改
    def get_content(self):
        if self.display_type == 1:
            context = {

            }
            return render_to_string('blog/sidebar/search.html', context=context)
        elif self.display_type == 2:
            context = {

            }
            return render_to_string('blog/sidebar/new_post.html', context=context)
        elif self.display_type == 3:
            context = {

            }
            return render_to_string('blog/sidebar/hot_post.html', context=context)
        elif self.display_type == 4:  
            context = {

            }
            return render_to_string('blog/sidebar/commment.html', context=context)
        elif self.display_type == 5:   # 文章归档
            context = {

            }
            return render_to_string('blog/sidebar/archives.html', context=context)
        elif self.display_type == 6:   # 自定义侧边栏
           
            return self.content   # 在侧边栏直接使用这里的html，模板中必须使用safe过滤器去渲染HTML

blog/views.py
from django.shortcuts import get_object_or_404, render



from django.contrib.auth.models import User
from .models import Category,Post
from django.db.models import Q, F
from django.core.paginator import Paginator


# Create your views here.


def index(request):
    post_list = Post.objects.all()   # 查询到所有的文章,queryset
    # 分页方法
    paginator = Paginator(post_list, 2)  # 第二个参数2代表每页显示几个
    page_number = request.GET.get('page')   # http://assas.co/?page=1 (页码)
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, 'blog/index.html', context)

def category_list(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    # 获取当前分类下的所有文章
    posts = category.post_set.all()
    paginator = Paginator(posts, 2)  # 第二个参数2代表每页显示几个
    page_number = request.GET.get('page')   # http://assas.co/?page=1 (页码)
    page_obj = paginator.get_page(page_number)
    context = {'category': category, 'page_obj': page_obj }
    return render(request, 'blog/list.html', context)

def post_detail(request, post_id):
    # 文章正文页
    post = get_object_or_404(Post, id=post_id)

    # 用文章id来实现的上下篇
    # prev_post = Post.objects.filter(id__lt=post_id).last()  # 上一篇
    # next_post = Post.objects.filter(id__gt=post_id).first() # 下一篇
    
    # 用发布日期来实现上下篇
    date_prev_post = Post.objects.filter(add_date__lt=post.add_date).last()
    date_next_post = Post.objects.filter(add_date__gt=post.add_date).first()
    Post.objects.filter(id=post_id).update(pv = F('pv') + 1) 

    context = {'post': post, 'prev_post': date_prev_post, 'next_post': date_next_post}
    return render(request, 'blog/detail.html', context)

def archives(request, year, month):
    # 文章归档列表页
    post_list = Post.objects.filter(add_date__year=year, add_date__month=month)
    context = {'post_list': post_list, 'year': year, 'month': month}
    return render(request, 'blog/archives_list.html', context )

def search(request):
    """ 搜索视图 """
    keyword = request.GET.get('keyword')
    # 没有搜索默认显示所有文章
    if not keyword:
        post_list = Post.objects.all()
    else:
        # 包含查询的方法，用Q对象来组合复杂查询，title__icontains 他两个之间用的是双下划线（__）链接
        post_list = Post.objects.filter(Q(title__icontains=keyword) | Q(desc__icontains=keyword) | Q(content__icontains=keyword))
    paginator = Paginator(post_list, 2)  # 第二个参数2代表每页显示几个
    page_number = request.GET.get('page')   # http://assas.co/?page=1 (页码)
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj
    }
    return render(request, 'blog/index.html', context )



def cloud_disk(request):
    user = User.objects.get(username=request.user)
    return render(request, 'blog/cloud_disk.html', {'user': user})

blog/templates/blog/archives_list.html
{% extends 'blog/base.html' %}

{% block title %} {{ year }}{{ month }}的归档{% endblock %}

{% block archives %}
    <!-- 显示当前分类模块 -->
    <div class="box">
        每月归档：{{ year }}年{{ month }}月
        <div class="tags has-addons is-pulled-right">
          <span class="tag">共</span>
          <span class="tag is-primary">{{ post_list.count }} 篇</span>
        </div>
    </div>
    <!-- 显示当前分类模块 end-->
{% endblock  %}

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static category %}
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %}欢迎来到北极来的企鹅的世界{% endblock %}</title>
	<!-- <link rel="stylesheet" href="{% static 'users/bulma.css' %}"> -->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
	<link rel="stylesheet" href="{% static 'users/styleCustom.css' %}">
	<link rel="shortcut icon" href="{% static 'users/images/icon.png' %}">
	<style>
	body {
		position: fixed;
		top: 0;
		left: 0;
		width: 100%;
		height: 100%;
		min-width: 1000px;
		z-index: -10;
		zoom: 1;
		background-color: #fff;
		background-repeat: no-repeat;
		background-size: cover;
		-webkit-background-size: cover;
		-o-background-size: cover;
		background-position: center 0;
	}
	</style>
</head>

<body background="{% static 'users/images/background.png' %}">

	<nav class="navbar is-light container" role="navigation" aria-label="main navigation">
			<div class="navbar-brand">
				<a class="navbar-item" href="/">
					<img src="{% static 'users/images/logo.png' %}" width="140" height="99">
				</a>

				<a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false"
					data-target="navbarBasicExample">
					<span aria-hidden="true"></span>
					<span aria-hidden="true"></span>
					<span aria-hidden="true"></span>
				</a>
			</div>

			<div id="navbarBasicExample" class="navbar-menu">
				<div class="navbar-start">

					{% block navbar-start %}
					<a class="navbar-item" href="/">
						首页
					</a>
					<a class="navbar-item" href="{% url 'blog:cloud_disk' %}">
						云盘
					</a>
					{% get_category_list as category_list %}
		
						{% for category in category_list %}
						<a class="navbar-item" href="{% url 'blog:category_list' category.id %}">
							{{ category.name }}
						</a>
						{% endfor %}
					{% endblock %}
				</div>


				<div class="navbar-end">
				<div class="navbar-end">
					<a href="https://space.bilibili.com/56999603?spm_id_from=333.1007.0.0" id='add' class=" navbar-item">
						<img src="{% static 'users/images/bilibili.png' %}">
					</a>
					<a href="https://github.com/Bjldqe" id='add' class=" navbar-item">
						<img src="{% static 'users/images/github.png' %}">
					</a>
				</div>
					{% block navbar-end %}
					<div class="navbar-item">
						{% if user.is_authenticated %}
						<div class="buttons">
							<a class="button is-link is-outlined" href="{% url 'users:user_profile' %}" target="_blank">
								<strong> {{ request.user.username }}</strong>
							</a>
							<a href="{% url 'users:logout' %}" class="button is-link">登出</a>
						</div>
						{% else %}
						<div class="buttons">
							<a class="button is-link is-outlined" href="{% url 'users:register' %}" target="_blank">
								<strong>注册</strong>
							</a>
							<a class="button is-link" href="{% url 'users:login' %}" target="_blank">
								登录
							</a>
						</div>
						{% endif %}
					</div>
					{% endblock %}
				</div>

			</div>
	</nav>
	<section class="section">
		<div class=" container">
			<div class="columns">
				<div class="column is-8">
					{% block section %}
					{% block archives %}{% endblock  %}
					
					{% if page_obj %}
					{% for post in page_obj %}
					<div class="box">
						<h1 class="is-size-5 has-text-weight-bold">
							<a href="{% url 'blog:post_detail' post.id %}"> {{ post.title }}</a>
						</h1>
						<div class=" is-size-7 has-text-grey-light pt-1 pb-1">
							<span class="mr-3">发布者：{{ post.owner }}</span> <span>发布日期：{{ post.add_date }}</span>
						</div>
						<!-- https://docs.djangoproject.com/zh-hans/3.2/ref/templates/builtins/#truncatechars  官方文档 -->
						<p class="mt-3">{{ post.desc|truncatechars:50 }}</p>
					</div>
					{% endfor %}
					{% else %}
					<div class="box">
						<p class="has-text-link">这里一片虚无...</p>
					</div>
					{% endif %}
					<!--  文档： https://docs.djangoproject.com/zh-hans/3.2/ref/paginator/#django.core.paginator.Paginator -->
					{% if page_obj %}
						<nav class="pagination is-centered" role="navigation" aria-label="pagination">
						{% if page_obj.has_previous %}
							<a class="pagination-previous" href="?page={{ page_obj.previous_page_number }}">Previous</a>
						{% endif %}
						{% if page_obj.has_next %}
						<a class="pagination-next" href="?page={{ page_obj.next_page_number }}">Next page</a>
						{% endif %}
						<ul class="pagination-list">
						{% if page_obj.has_previous %}
							<li><a class="pagination-link" aria-label="Goto page 45" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
						{% endif %}
							<li><a class="pagination-link is-current" aria-label="Page {{ page_obj.number }}" aria-current="page" href='?page={{ page_obj.number }}'>{{ page_obj.number }}</a></li>
						{% if page_obj.has_next %}
							<li><a class="pagination-link" href="?page={{ page_obj.next_page_number }}" aria-label="Goto page {{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
						{% endif %}
						</ul>
						</nav>
						{% endif %} 
					{% endblock %}
				</div>
				<div class="column is-4">

					{% block right %}
					{% get_sidebar_list as sidebar_list %}
					{% for sidebar in sidebar_list %}
					<div class="box">
						<h1 class=" is-size-5 title">{{ sidebar.title }}</h1>
						<p>{{ sidebar.get_content|safe }}</p>
					</div>
					
					{% endfor %}
					{% endblock %}

				</div>
			</div>

		</div>
	</section>

	{% block footer %}
	<!-- <footer class="footer container">
		<div class=" has-text-centered is-half is-offset-one-quarter ">
			没有更多内容了
		</div>
	</footer> -->
	{% endblock %}

</body>

</html>

blog/templates/blog/cloud_disk.html
{% extends 'blog/base.html' %}
{% block head %}
<title>云站点</title>
<style>
    div {
        text-align: center;
        /*可以让盒子内容（文字 行内元素 行内块元素）居中对齐*/
        width: 600px;
        height: 200px;
        background-color: pink;
        /* margin: 0 auto; 通俗写法 0 auto  上下是 0  左右是auto  自动  水平居中对齐 */
        /* margin-left: auto;
		 margin-right: auto; 自动充满*/
        /* margin: auto; 上下左右都是auto*/
        margin: auto;

    }
</style>
{% load static %}
{% endblock head %}
{% block section %}
<div class="box">
    <button type="button" id="btn" class="button is-text" onclick="window.location.href = 'https://bjldqe.lanzoup.com/i063Z0p6nd3g'">汇报PPT</button>
</div>



{% endblock %}

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block section %}
<div class="box">
    <h1 class="is-size-5 has-text-weight-bold">
        <a> {{ post.title }}</a>
    </h1>
    <div class=" is-size-7 has-text-grey-light pt-1 pb-1">
        <span class="mr-3">发布者：{{ post.owner }}</span> <span>发布日期：{{ post.add_date }}</span> <span>阅读量：{{ post.pv }}</span>
    </div>
    <div class="content">
        {{ post.content|safe }}
    </div>
</div>

<div class="box">
    <div class="level">
        <div class="level-left">
            
            {% if prev_post %}
            <span>上一篇：</span><a href="{% url 'blog:post_detail' prev_post.id %}" class="level-item">{{ prev_post.title }}</a>
            {% else %}
            <span class=" has-text-danger-dark is-size-7">没有上一篇了~</span>
            {% endif %}
        </div>
        <div class="level-right">
            {% if next_post %}
            <span>下一篇：</span><a href="{% url 'blog:post_detail' next_post.id %}" class="level-item">{{ next_post.title }}</a>
            {% else %}
            <span class=" has-text-danger-dark is-size-7">已经是最后一篇了~</span>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
    

blog/templates/blog/list.html
{% extends 'blog/base.html' %}