blog/urls.py
from django.urls import path 
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.index, name='index'),
    path('category/<int:category_id>/', views.category_list, name='category_list'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    path('search/', views.search, name='search'),
    path('cloud_disk/',views.cloud_disk, name='cloud_disk'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

from utils.upload import upload_file

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('', include('blog.urls')) ,
    path('uploads/', upload_file, name='uploads'),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "BJLDQE管理后台"
admin.site.index_title = "BJLDQE管理后台"
admin.site.site_title = "管理员已上线"

users/urls.py
from django.urls import path
from . import views

app_name = 'users'   # 定义一个命名空间，用来区分不同应用之间的链接地址
urlpatterns = [ 
    path('login', views.login_view, name='login'),
    path('register/', views.register, name='register'),
    path('active/<active_code>',views.active_user,name='active_user'),
    path('forget_pwd/', views.forget_pwd, name='forget_pwd'),   # 找回密码发送邮件页面
    path('forget_pwd_url/<active_code>', views.forget_pwd_url, name='forget_pwd_url'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('editor_users/', views.editor_users, name='editor_users'), 
    path('logout/', views.logout_view, name='logout'),



]

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model):
    USER_GENDER_TYPE = (
        ('male', '男'),
        ('female', '女'),
    )
    owner = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name = '用户')
    nick_name = models.CharField('称呼', max_length=50, blank=True, default='')
    birthday = models.DateField('生日', null=True, blank=True)
    gender = models.CharField('性别', max_length=6, choices=USER_GENDER_TYPE, default='male')
    address = models.CharField('位置', max_length=100, blank=True, default='')
    #qq_number = models.CharField('QQ', max_length=50, blank=True, default='')
    signature = models.CharField('签名', max_length=200, blank=True, default='这个人什么也没有留下!(>_<)')
    desc = models.TextField('个人简介', max_length=200, blank=True, default='')
    image = models.ImageField(upload_to='images/%Y/%m', default='images/default.png', max_length=100, verbose_name = '头像')

    class Meta:
        verbose_name = '用户数据'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.owner.username
    
class EmailVerifyRecord(models.Model):
    """邮箱验证记录"""
    SEND_TYPE_CHOICES = (
        ('register', '注册'),
        ('forget', '找回密码'),
    )

    code = models.CharField('验证码', max_length=20)
    email = models.EmailField('邮箱', max_length=50)
    send_type = models.CharField(choices=SEND_TYPE_CHOICES, max_length=10, default='register')
    send_time = models.DateTimeField('时间', auto_now_add=True)

    class Meta:
        verbose_name = '验证码'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.code
    


users/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import UserProfile

class LoginForm(forms.Form):
    username = forms.CharField(label='用户名', max_length=32,widget=forms.TextInput(attrs={
        'class':'input','placeholder':'请输入用户名/邮箱'
    }))
    password = forms.CharField(label='密码', min_length=6, widget=forms.PasswordInput(attrs={
        'class':'input','placeholder':'请输入密码'
    }))

    def clean_password(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        if username == password:
            raise forms.ValidationError('密码不可与用户名相同')
        return password
    
class RegisterForm(forms.ModelForm):
    email = forms.EmailField(label='邮箱', min_length=3, widget=forms.EmailInput(attrs={
        'class': 'input', 'placeholder': '请输入邮箱'}))
    password = forms.CharField(label='密码', min_length=6, widget=forms.PasswordInput(attrs={
        'class': 'input', 'placeholder': '请输入密码密码'}))
    password1 = forms.CharField(label='请再次输入密码', min_length=6, widget=forms.PasswordInput(attrs={
        'class': 'input', 'placeholder': '两次密码请保持一致'}))

    class Meta:
        model = User
        fields = ('email', 'password')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        exists = User.objects.filter(email=email).exists()
        if exists:
            raise forms.ValidationError('该邮箱已被注册!')
        return email

    def clean_password1(self):
        data = self.cleaned_data
        password = data['password']
        password1 = data['password1']
        if password != password1:
            raise forms.ValidationError('两次输入的密码不一致,请重新输入!')
        return password
class ForgetPwdForm(forms.Form):
    """ 填写邮箱地址表单 """
    email = forms.EmailField(label='请输入你的邮箱', min_length=4, widget=forms.EmailInput(attrs={
        'class': 'input', 'placeholder': '用户名/邮箱'
    }))

class ModifyPwdForm(forms.Form):
	"""Form definition for UserProfile."""
	password = forms.CharField(label='输入新密码', min_length=6, 
		widget=forms.PasswordInput(attrs={'class':'input', 'placeholder':'输入新密码'}))

class UserForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'input', 'disabled':'disabled'
    }))

    class Meta:
        model = User
        fields = ('email',)


class UserProfileForm(forms.ModelForm):
    """Form definition for UserInfo."""
 
    class Meta:
        """Meta definition for UserInfoform."""

        model = UserProfile
        fields = ('nick_name','desc', 'signature', 'birthday',  'gender', 'address', 'image')

users/views.py
from telnetlib import LOGOUT
from django.shortcuts import render,HttpResponse,redirect
from django.contrib.auth import authenticate, login,logout

from users.models import EmailVerifyRecord
from utils.email_send import send_register_email
from .forms import ForgetPwdForm, LoginForm, ModifyPwdForm, RegisterForm,UserForm,UserProfileForm
from django.contrib.auth.backends import ModelBackend
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password
from django.db.models import Q
from .models import UserProfile  # 引入用户模型字段
from django.contrib.auth.decorators import login_required

# Create your views here.from .models import UserProfile  # 引入用户模型字段


class MyBackend(ModelBackend):
    '''邮箱登录注册'''
    def authenticate(self, request, username=None, password=None):
        try:
            user = User.objects.get(Q(username=username)|Q(email=username))
            if user.check_password(password):   # 加密明文密码
                return user
        except Exception as e:
            return None

def login_view(request):
    #if request.method == 'POST':   # 判断采用的是何种请求
    #    username = request.POST['username']  # request.POST[]或request.POST.get()获取数据
    #    password = request.POST['password']
        # 与数据库中的用户名和密码比对，django默认保存密码是以哈希形式存储，并不是明文密码，这里的password验证默认调用的是User类的check_password方法，以哈希值比较。
    #    user = authenticate(request, username=username, password=password)
        # 验证如果用户不为空
    #   if user is not None:
            # login方法登录
    #      # 返回登录成功信息
    #       return HttpResponse('登陆成功')
    #    else:
            # 返回登录失败信息
    #       return HttpResponse('登陆失败,请重试')
    
    if request.method != 'POST':
        form = LoginForm()
    else:
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                # 登陆成功跳转到指定页面
                return redirect('users:user_profile')
            else:
                # 验证不通过提示！
                return HttpResponse("账号或密码错误,请重试")
    return render(request, 'users/login.html', {'form': form})

def register(request):
    if request.method != 'POST':
        form = RegisterForm()
    else:
        form = RegisterForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.username = form.cleaned_data.get('email')  
            new_user.set_password(form.cleaned_data['password'])
            new_user.save()
             # 让username等于邮箱即可
            send_register_email(form.cleaned_data.get('email') ,'register')
            return  HttpResponse('注册成功,请返回用户界面登录') #redirect('users:login')
    context = {'form': form}
    return render(request, 'users/register.html', context)

def active_user(request, active_code):
    """查询验证码"""
    print(active_code)
    all_records = EmailVerifyRecord.objects.filter(code=active_code)
    print(all_records)
    if all_records:
        for record in all_records:
            email = record.email
            print(email)
            user = User.objects.get(email=email)
            print(user)
            user.is_staff = True
            user.save()
    else:
        return HttpResponse('邀请被销毁了！')
    return redirect('users:login')

def forget_pwd(request):
    """ 找回密码 """
    if request.method == 'GET':
        form = ForgetPwdForm()
    elif request.method == 'POST':
        form = ForgetPwdForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            exists = User.objects.filter(email=email).exists()
            if exists:
                # 发送邮件
                send_register_email(email, 'forget')
                return HttpResponse('邮件已经发送，请查收！')
            else:
                return HttpResponse('邮箱未注册，请前往注册！')

    return render(request, 'users/forget_pwd.html', {'form': form})

def forget_pwd_url(request, active_code):
    if request.method != 'POST':
        form = ModifyPwdForm()
    else:
        form = ModifyPwdForm(request.POST)
        if form.is_valid():
            record = EmailVerifyRecord.objects.get(code=active_code)
            email = record.email
            user = User.objects.get(email=email)
            user.username = email
            user.password = make_password(form.cleaned_data.get('password'))
            user.save()
            return HttpResponse('密码修改成功')
        else:
            return HttpResponse('密码修改失败')

    return render(request, 'users/reset_pwd.html', {'form': form})

@login_required(login_url='users:login')   # 设置登录后才能访问，如果没有登陆，就跳转到登录界面
def user_profile(request):
    user = User.objects.get(username=request.user)
    return render(request, 'users/user_profile.html', {'user': user})


def logout_view(request):
    ''' 登出 '''
    logout(request)
    return redirect('users:login')

@login_required(login_url='users:login')   # 登录之后允许访问
def editor_users(request):
    """ 编辑用户信息 """
    user = User.objects.get(id=request.user.id)
    if request.method == "POST":
        try:
            userprofile = user.userprofile
            form = UserForm(request.POST, instance=user)
            user_profile_form = UserProfileForm(request.POST, request.FILES, instance=userprofile)  # 向表单填充默认数据
            if form.is_valid() and user_profile_form.is_valid():
                form.save()
                user_profile_form.save()
                return redirect('users:user_profile')
        except UserProfile.DoesNotExist:   # 这里发生错误说明userprofile无数据
            form = UserForm(request.POST, instance=user)       # 填充默认数据 当前用户
            user_profile_form = UserProfileForm(request.POST, request.FILES)  # 空表单，直接获取空表单的数据保存
            if form.is_valid() and user_profile_form.is_valid():
                form.save()
                # commit=False 先不保存，先把数据放在内存中，然后再重新给指定的字段赋值添加进去，提交保存新的数据
                new_user_profile = user_profile_form.save(commit=False)
                new_user_profile.owner = request.user
                new_user_profile.save()

                return redirect('users:user_profile')
    else:
        try:
            userprofile = user.userprofile
            form = UserForm(instance=user)
            user_profile_form = UserProfileForm(instance=userprofile) 
        except UserProfile.DoesNotExist:
            form = UserForm(instance=user)
            user_profile_form = UserProfileForm()  # 显示空表单
    return render(request, 'users/editor_users.html', locals())



users/templates/users/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block head %}<title>登录页面</title>{% endblock head %}

<link rel="stylesheet" href="{% static 'users/bulma.css' %}">
<link rel="stylesheet" href="{% static 'users/styleCustom.css' %}">
<link rel="shortcut icon" href="{% static 'users/images/icon.png' %}">
    <style>
        body {
            position:fixed;
            top: 0;
            left: 0;
            width:100%;
            height:100%;
            min-width: 1000px;
            z-index:-10;
            zoom: 1;
            background-color: #fff;
            background-repeat: no-repeat;
            background-size: cover;
            -webkit-background-size: cover;
            -o-background-size: cover;
            background-position: center 0;
        }
    </style>
</head>

<body background="{% static 'users/images/background.png' %}">
    <!-- <div class="container"> -->

        {% block content %}

        {% endblock content %}

    <!-- </div> -->


</body>

</html>

users/templates/users/editor_users copy.html
{% extends 'users/user_profile.html' %}
{% load i18n static %}

{% block title %}
<li class="is-active"><a>编辑信息</a></li>
{% endblock title %}

{% block content %}
<div class="content">
    <fieldset disabled style="margin-bottom: 1em">
        <div class="field is-horizontal">
            <div class="field-label is-normal">
                <label class="label">用户名</label>
            </div>
            <div class="field-body">
                <div class="field">
                    <p class="control is-expanded has-icons-left">
                        <input class="input" type="text" placeholder="Name" value="{{ user.username }}">
                        <span class="icon is-small is-left">
                            <i class="fas fa-user"></i>
                        </span>
                    </p>
                </div>
            </div>
        </div>
    </fieldset>


    <form action="{% url 'users:editor_users' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="field is-horizontal">
            <div class="field-label is-normal">
                <label for="{{ form.email.id_for_label }}" class="label">{{ form.email.label }}</label>
            </div>
            <div class="field-body">
                <div class="field">
                    <div class="control">
                        {{ form.email }}
                    </div>
                </div>
            </div>
        </div>
        {% for field in user_profile_form %}
        <div class="field is-horizontal">
            <div class="field-label is-normal">
                <label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
            </div>
            <div class="field-body">
                <div class="field">
                    <div class="control">
                        {{ field }}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        <input class=" button is-primary is-pulled-right" type="submit" value="{% trans '保存' %}">
        <div class=" is-clearfix"></div>

    </form>
</div>
{% endblock content %}

users/templates/users/editor_users.html
{% extends 'users/user_profile.html' %}

<!-- 如何覆盖掉继承模板文件中原有的东西 -->


{% block title %}
<li class="is-active"><a>编辑信息</a></li>
{% endblock %}

{% block content %}

<!-- 官方文档： https://docs.djangoproject.com/zh-hans/3.2/topics/forms/ -->
<form action="{% url 'users:editor_users' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="field is-horizontal">
        <div class="field-label is-normal">
            <label for="{{ form.email.id_for_label }}" class="label">{{ form.email.label }}</label>
        </div>
        <div class="field-body">
            <div class="field">
                <div class="control">
                    {{ form.email }}
                </div>
            </div>
        </div>
    </div>
    {% for field in user_profile_form %}
    <div class="field is-horizontal">
        <div class="field-label is-normal">
            <label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
        </div>
        <div class="field-body">
            <div class="field">
                <div class="control">
                    {{ field }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <input class=" button is-primary is-pulled-right" type="submit" value="保存">
    <div class=" is-clearfix"></div>

</form>
{% endblock %}

users/templates/users/forget_pwd.html
{% extends 'users/base.html' %}

{% block head %}
{% load static %}
<link rel="shortcut icon" href="{% static 'users/images/icon.png' %}">
<title>找回密码</title>
<style>
    div {
        text-align: center;
        /*可以让盒子内容（文字 行内元素 行内块元素）居中对齐*/
        width: 600px;
        height: auto;
        background-color: pink;
        /* margin: 0 auto; 通俗写法 0 auto  上下是 0  左右是auto  自动  水平居中对齐 */
        /* margin-left: auto;
		 margin-right: auto; 自动充满*/
        /* margin: auto; 上下左右都是auto*/
        margin: auto;

    }
</style>
<audio src="{% static 'users/music/bgm.mp3' %}" id="aud" autoplay="autoplay" controls="controls"
        preload="auto"></audio>
{% endblock head %}

{% block content %}
<div class="box">
    <a href="/" class=" navbar-item">
    <img src="{% static 'users/images/logo.png' %}" width="140" height="99" alt="logo">
    </a>
    <h1 class="is-uppercase has-text-centered has-text-weight-bold">Do not Worry!
        <br><span class="tag">找回密码</span>
    </h1>
    <hr class=" dropdown-divider">
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {{ form.errors }}
        <a href="{% url 'users:login' %}" id="load">
            <button class="button is-text " type="button" style="margin-top: 1em;">返回登录</button>
        </a>
        <input type="submit" style="margin-top: 1em;" class="button is-link " value="发送邮件">
    </form>
</div>

{% endblock content %}

users/templates/users/login.html
{% extends 'users/base.html' %}


{% block head %}
{% load static %}
<link rel="shortcut icon" href="{% static 'users/images/icon.png' %}">
<title>登录页面</title>
<style>
    div {
        text-align: center;
        /*可以让盒子内容（文字 行内元素 行内块元素）居中对齐*/
        width: 600px;
        height: auto;
        background-color: pink;
        /* margin: 0 auto; 通俗写法 0 auto  上下是 0  左右是auto  自动  水平居中对齐 */
        /* margin-left: auto;
		 margin-right: auto; 自动充满*/
        /* margin: auto; 上下左右都是auto*/
        margin: auto;

    }
</style>
<audio src="{% static 'users/music/bgm.mp3' %}" id="aud" autoplay="autoplay" controls="controls"
        preload="auto"></audio>

{% endblock head %}


{% block content %}
<div class="box">
    <a href="/" class=" navbar-item">
    <img src="{% static 'users/images/logo.png' %}" width="140" height="99" alt="logo">
    </a>
    <h1 class="is-uppercase has-text-centered has-text-weight-bold">Welcome!
        <br><span class="tag">立即登录,顷刻访问博主北极来的企鹅的别样世界！</span>
        </h1>
        <hr class=" dropdown-divider">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <a class=" is-pulled-right is-size-7" href="{% url 'users:forget_pwd' %}">忘记密码?</a>
            <!-- <div class=" is-clearfix"></div> -->
            <a href="{% url 'users:register' %}" id="load">
                <button class="button is-text "  type="button" style="margin-top: 1em;">注册</button>
            </a>
            <input type="submit" style="margin-top: 1em;" class="button is-link " value="登录">
        </form>
    </div>
{% endblock content %}

users/templates/users/register.html
{% extends 'users/base.html' %}

{% block head %}
{% load static %}
<link rel="shortcut icon" href="{% static 'users/images/icon.png' %}">

<title>用户注册</title>
<style>
    div {
        text-align: center;
        /*可以让盒子内容（文字 行内元素 行内块元素）居中对齐*/
        width: 600px;
        height: auto;
        background-color: pink;
        /* margin: 0 auto; 通俗写法 0 auto  上下是 0  左右是auto  自动  水平居中对齐 */
        /* margin-left: auto;
		 margin-right: auto; 自动充满*/
        /* margin: auto; 上下左右都是auto*/
        margin:  auto;

    }
    </style>
<audio src="{% static 'users/music/bgm.mp3' %}" id="aud" autoplay="autoplay" controls="controls"
        preload="auto"></audio>
{% endblock head %}


{% block content %}
<div class="box">
    <a href="/" class=" navbar-item">
    <img src="{% static 'users/images/logo.png' %}" width="140" height="99" alt="logo">
    </a>
    <h1 class="is-uppercase has-text-centered has-text-weight-bold">Welcome!
        <br><span class="tag">现在注册一个账号,与博主北极来的企鹅一同畅游世界</span>
    </h1>
    <hr class=" dropdown-divider">
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <a href="{% url 'users:login' %}" id="load">
            <button class="button is-text " type="button" style="margin-top: 1em;">返回登录</button>
        </a>
        <input type="submit" style="margin-top: 1em;" class="button is-link " value="注册">
    </form>

</div>
{% endblock content %}

users/templates/users/reset_pwd.html
{% extends 'users/base.html' %}
{% block head %}
{% load static %}
<link rel="shortcut icon" href="{% static 'users/images/icon.png' %}">

<title>修改密码</title>
<style>
    div {
        text-align: center;
        /*可以让盒子内容（文字 行内元素 行内块元素）居中对齐*/
        width: 600px;
        height: auto;
        background-color: pink;
        /* margin: 0 auto; 通俗写法 0 auto  上下是 0  左右是auto  自动  水平居中对齐 */
        /* margin-left: auto;
		 margin-right: auto; 自动充满*/
        /* margin: auto; 上下左右都是auto*/
        margin: auto;

    }
</style>
<audio src="{% static 'users/music/bgm.mp3' %}" id="aud" autoplay="autoplay" controls="controls"
        preload="auto"></audio>
{% endblock head %}


{% block content %}
<div class="box">
    <a href="/" class=" navbar-item">
    <img src="{% static 'users/images/logo.png' %}" width="140" height="99" alt="logo">
    </a>
    <h1 class="is-uppercase has-text-centered has-text-weight-bold">Reset Now!
        <br><span class="tag">修改密码</span>
    </h1>
    <hr class=" dropdown-divider">
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {{ form.errors }}
        <a href="{% url 'users:login' %}" id="load">
            <button class="button is-text " type="button" style="margin-top: 1em;">返回登录</button>
        </a>
        <input type="submit" style="margin-top: 1em;" class="button is-link " value="确定">
    </form>
</div>

{% endblock content %}